include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    lines_longer_than_80_chars: ignore

linter:
  rules:
    public_member_api_docs: false